### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by hungvalen** [fawazahmed0/Moodle-Hacking#6]
Sorry, for bothering, I have a question if I take a test on moodle, I have almost half the right answer, but I don't know which is the correct answer so can you show me . Thank you so much for reading this.

**Comment by ibocan24** [comment]
Hey how did you get the answers which you got?

**Comment by ibocan24** [comment]
@hungvalen

**Comment by fawazahmed0** [comment]
Please see [this](https://github.com/fawazahmed0/Moodle-Hacking#note)
